services:
    darkanakin41.core.menu:
        public: true
        class: Darkanakin41\CoreBundle\Menu\MenuService
        arguments: ["@service_container"]
        tags:
        - { name: twig.extension }
    darkanakin41.core.date:
        public: true
        class: Darkanakin41\CoreBundle\Service\DateService
        tags:
        - { name: twig.extension }
    darkanakin41.core.entity:
        public: true
        class: Darkanakin41\CoreBundle\Service\EntityRenderService
        arguments: ["@service_container"]
        tags:
        - { name: twig.extension }
    darkanakin41.core.slugify:
      public: true
      class: Darkanakin41\CoreBundle\Service\Slugify
      tags:
          - { name: twig.extension }
