services:
    Darkanakin41\CoreBundle\Menu\MenuService:
        public: true
        class: Darkanakin41\CoreBundle\Menu\MenuService
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    Darkanakin41\CoreBundle\Service\DateService:
        public: true
        class: Darkanakin41\CoreBundle\Service\DateService
        tags:
            - { name: twig.extension }

    Darkanakin41\CoreBundle\Service\EntityRenderService:
        public: true
        class: Darkanakin41\CoreBundle\Service\EntityRenderService
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    Darkanakin41\CoreBundle\Service\SlugifyService:
        public: true
        class: Darkanakin41\CoreBundle\Service\SlugifyService
        tags:
            - { name: twig.extension }

    darkanakin41.core.menu:
        alias: Darkanakin41\CoreBundle\Menu\MenuService
        public: true
    darkanakin41.core.date:
        alias: Darkanakin41\CoreBundle\Service\DateService
        public: true
    darkanakin41.core.entity:
        alias: Darkanakin41\CoreBundle\Service\EntityRenderService
        public: true
    darkanakin41.core.slugify:
        alias: Darkanakin41\CoreBundle\Service\SlugifyService
        public: true
